version: "3.7"
   
services:
  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /home/db/postgres_data:/var/lib/postgresql/data:z
    ports:
      - "5432:5432"
    networks: 
      - main
  web:
    build: .
    command: bash start.sh
    volumes:
      - .:/code
    expose:
      - "8000"
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    image: inoa-challenge_web:latest
    networks:
      - main
    depends_on:
      - db

networks:
  main:  
  
