version: "3.7"
   
services:
  db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - /home/db/postgres_data:/var/lib/postgresql/data:z
    ports:
      - "5432:5432"
    networks: 
      - main
    env_file:
      - ./.env
  web:
    build: .
    command: bash start.sh
    volumes:
      - .:/code
    expose:
      - "8000"
    ports:
      - "8000:8000"      
    image: inoa-challenge_web:latest
    networks:
      - main
    depends_on:
      - db
    env_file:
      - ./.env
networks:
  main:  
  
