# Generated by Django 3.1.7 on 2021-03-07 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_asset_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='stop_loss_price',
            new_name='lower_limit_price',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='stop_limit_price',
            new_name='upper_limit_price',
        ),
    ]
